version: '2.4'
services:
  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - dynamodb_data:/home/dynamodblocal/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  dynamodb-init:
    image: amazon/aws-cli
    container_name: dynamodb-init
    depends_on:
      - dynamodb-local
    volumes:
      - ./infrastructure/driven-adapters/dynamo-db/src/main/java/com/muebles/stats/dynamodb/config/init-dynamodb.sh:/init-dynamodb.sh
    entrypoint: ["/bin/sh", "-c", "sleep 10 && sh /init-dynamodb.sh"]

  sonarqube-db:
    image: postgres:13
    container_name: sonarqube-db
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - sonarqube_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  sonarqube:
    image: sonarqube:9.9-community
    container_name: sonarqube
    depends_on:
      - sonarqube-db
    ports:
      - "9000:9000"
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://sonarqube-db:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  stats-service:
    build:
      context: .
      dockerfile: deployment/Dockerfile
    container_name: stats-service
    depends_on:
      rabbitmq:
        condition: service_healthy
      dynamodb-local:
        condition: service_started
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS= -Xshareclasses:name=cacheapp,cacheDir=/cache,nonfatal -XX:+UseContainerSupport -XX:MaxRAMPercentage=70 -Djava.security.egd=file:/dev/./urandom
      - SPRING_RABBITMQ_HOST=rabbitmq
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
      - AWS_DYNAMODB_ENDPOINT=http://dynamodb-local:8000
    # Si tu app necesita variables de entorno adicionales, agrégalas aquí

volumes:
  dynamodb_data:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
  sonarqube_db:
