server:
  port: ${SERVER_PORT:8080}
spring:
  application:
    name: ${SPRING_APPLICATION_NAME:stats-service}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  devtools:
    add-properties: false
    restart:
      enabled: false
  h2:
    console:
      enabled: ${H2_CONSOLE_ENABLED:true}
      path: ${H2_CONSOLE_PATH:/h2}
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:rabbitmq}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
aws:
  accessKey: ${AWS_ACCESS_KEY:dummy}
  secretKey: ${AWS_SECRET_KEY:dummy}
  region: ${AWS_REGION:us-west-2}
  dynamodb:
    endpoint: ${DYNAMODB_ENDPOINT:http://dynamodb-local:8000}
management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE:health,prometheus}
  endpoint:
    health:
      probes:
        enabled: ${HEALTH_PROBES_ENABLED:true}
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:4200,http://localhost:8080}
springdoc:
  api-docs:
    enabled: ${SPRINGDOC_API_DOCS_ENABLED:true}
  swagger-ui:
    enabled: ${SPRINGDOC_SWAGGER_UI_ENABLED:true}
  packages-to-scan: ${SPRINGDOC_PACKAGES_TO_SCAN:com.muebles.stats.api}
